# Generated by Django 4.1.4 on 2023-07-05 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mikrotik',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('mc', models.CharField(max_length=100, verbose_name='name')),
                ('proyecto', models.CharField(blank=True, choices=[('MC', 'MC'), ('Otro', 'Otro')], default='MC', max_length=100, null=True, verbose_name='Proyecto')),
                ('serie', models.CharField(blank=True, default='Null', max_length=50, null=True, verbose_name='type')),
                ('type', models.CharField(blank=True, choices=[('tipo_A', 'tipo_A'), ('tipo_B', 'tipo_B')], default='tipo_A', max_length=50, null=True, verbose_name='type')),
                ('p1', models.IntegerField(blank=True, null=True, verbose_name='p1')),
                ('p2', models.IntegerField(blank=True, null=True, verbose_name='p2')),
                ('p3', models.IntegerField(blank=True, null=True, verbose_name='p3')),
                ('p4', models.IntegerField(blank=True, null=True, verbose_name='p4')),
                ('p5', models.IntegerField(blank=True, null=True, verbose_name='p5')),
                ('p6', models.IntegerField(blank=True, null=True, verbose_name='p6')),
                ('p7', models.IntegerField(blank=True, null=True, verbose_name='p7')),
                ('p8', models.IntegerField(blank=True, null=True, verbose_name='p8')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
            ],
            options={
                'verbose_name': 'Mikrotik',
                'verbose_name_plural': 'Mikrotik',
                'ordering': ['-created'],
            },
        ),
    ]
