# Generated by Django 4.1.4 on 2023-07-05 23:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('ip', models.CharField(max_length=100, verbose_name='ip')),
                ('ssh_user', models.CharField(max_length=100, verbose_name='ssh user')),
                ('ssh_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='ssh password')),
                ('ftp_port', models.IntegerField(blank=True, default='22', null=True, verbose_name='type')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
            ],
            options={
                'verbose_name': 'Connection',
                'verbose_name_plural': 'Connection',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='mikrotik',
            name='id_connection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='get_mikrotik', to='mikrotik.connection', verbose_name='Connection'),
        ),
    ]
