# Generated by Django 4.1.3 on 2022-12-21 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("usuario", models.CharField(max_length=200, verbose_name="usuario")),
                ("password", models.CharField(max_length=200, verbose_name="password")),
                ("ip", models.CharField(max_length=50, verbose_name="ip")),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha creacion"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ultima modificacion"
                    ),
                ),
            ],
            options={
                "verbose_name": "Camera",
                "verbose_name_plural": "Cameras",
                "ordering": ["-created"],
            },
        ),
    ]
