# Generated by Django 4.1.4 on 2022-12-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_camera_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='serial_no',
            field=models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='Numero de serie'),
        ),
    ]
