# Generated by Django 4.1.5 on 2023-01-19 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_camera_serial_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEncode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('Compression', models.CharField(default='H.264', max_length=100, verbose_name='Compression')),
                ('CustomResolutionName', models.CharField(blank=True, default='720p', max_length=100, null=True, verbose_name='Numero de serie')),
                ('SmartCodec', models.CharField(default='Off', max_length=100, verbose_name='SmartCodec')),
                ('FPS', models.IntegerField(default=4, verbose_name='FPS')),
                ('BitRateControl', models.CharField(default='VBR', max_length=100, verbose_name='BitRateControl')),
                ('Quality', models.IntegerField(default=4, verbose_name='Quality')),
                ('BitRate', models.IntegerField(default=512, verbose_name='BitRate')),
                ('Language', models.CharField(default='English', max_length=100, verbose_name='Language')),
                ('CurrentTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CurrentTime')),
                ('Channel', models.IntegerField(default=0, verbose_name='Channel')),
                ('TypeEncode', models.IntegerField(default=0, verbose_name='TypeEncode')),
                ('TypeStream', models.CharField(default='Main Stream', max_length=100, verbose_name='TypeStream')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
            ],
            options={
                'verbose_name': 'VideoEncode',
                'verbose_name_plural': 'VideoEncode',
                'ordering': ['-created'],
            },
        ),
    ]
