# Generated by Django 4.1.4 on 2023-01-20 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_videoencode'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='videoencode_config_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='get_camara', to='monitor.videoencode', verbose_name='Configuracion de video'),
            preserve_default=False,
        ),
    ]
