# Generated by Django 4.1.5 on 2023-01-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_alter_camera_videoencode_config_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoencode',
            name='VideoEnable',
            field=models.CharField(blank=True, default='true', max_length=20, null=True, verbose_name='Video Enable'),
        ),
    ]
