# Generated by Django 4.1.4 on 2023-01-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_sitio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitio',
            name='active',
        ),
        migrations.AlterField(
            model_name='sitio',
            name='ip',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Ip'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='is_alive',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Is alive'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status'),
        ),
    ]
