# Generated by Django 4.1.4 on 2023-01-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_remove_sitio_active_alter_sitio_ip_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sitio',
        ),
    ]
