# Generated by Django 4.1.4 on 2023-01-26 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0001_initial'),
        ('monitor', '0015_delete_sitio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoEncode',
            new_name='Config',
        ),
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['-created'], 'verbose_name': 'Config', 'verbose_name_plural': 'Config'},
        ),
    ]
