# Generated by Django 4.1.4 on 2023-01-27 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0002_remove_sitio_videoencode_config_id'),
        ('monitor', '0016_rename_videoencode_config_alter_config_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='sitio_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='get_config', to='sitios.sitio', verbose_name='Sitio'),
            preserve_default=False,
        ),
    ]
