# Generated by Django 4.1.4 on 2023-01-27 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0003_config_stream_channel'),
        ('monitor', '0017_config_sitio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='videoencode_config_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_camera', to='sitios.config', verbose_name='Configuracion de video'),
        ),
        migrations.DeleteModel(
            name='Config',
        ),
    ]
