version: "3.7"

services:
  redis:
    restart: unless-stopped
    image: 'redis'
    ports:
      - '6379:6379'
  app:
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1  #
    container_name: app
    build: ./webapp
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./webapp:/app
  
  #cexporter:
  #  restart: unless-stopped
  #  container_name: cexporter
  #  build: ./webapp/celery_exporter
  #  ports:
  #    - "5530:5530"
  #  depends_on:
  #    - redis

  #  volumes:
  #    - ./webapp/celery_exporter:/app

  worker:
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1  #
    build:
      context: ./webapp
    hostname: worker
    entrypoint: celery
    command: -A app worker --loglevel=info --concurrency=10
    volumes:
      - ./webapp:/app
    depends_on:
      - redis

  flower: 
    restart: unless-stopped 
    image: mher/flower
    command: celery --broker=redis://redis:6379/0 flower --address=0.0.0.0 --port=5555
    ports:  
      - '5555:5555'
    depends_on:
      - redis

  celery-beat:
    restart: unless-stopped
    build: ./webapp
    command: celery -A app beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./webapp:/app
    environment:
      - DEBUG=1
    depends_on:
      - redis
  
  
