version: "3.7"

services:
  app:
    restart: always
    container_name: app
    build: ./dahua_api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./dahua_api:/app
  
  cexporter:
    restart: always
    container_name: cexporter
    build: ./dahua_api/celery_exporter
    ports:
      - "5530:5530"
    depends_on:
      - redis

    volumes:
      - ./dahua_api/celery_exporter:/app

  worker:
    restart: always
    build:
      context: ./dahua_api
    hostname: worker
    entrypoint: celery
    command: -A app worker --loglevel=info --autoscale=10,2
    volumes:
      - ./dahua_api:/app
    depends_on:
      - redis

  flower:  
    restart: always
    image: mher/flower
    command: celery --broker=redis://redis:6379/0 flower --address=0.0.0.0 --port=5555
    ports:  
      - '5555:5555'
    depends_on:
      - redis

  celery-beat:
    restart: always
    build: ./dahua_api
    command: celery -A app beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./dahua_api:/app
    environment:
      - DEBUG=1
    depends_on:
      - redis
  
  redis:
    restart: always
    image: 'redis'
    ports:
      - '6379:6379'
