# Generated by Django 4.1.4 on 2023-02-03 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('type', models.CharField(blank=True, choices=[('every-hours', 'every-hours'), ('every-time', 'every-time')], default='every-hours', max_length=50, null=True, verbose_name='type')),
                ('value', models.IntegerField(blank=True, null=True, verbose_name='value')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='time')),
                ('repeat', models.IntegerField(blank=True, null=True, verbose_name='repeats per day')),
                ('priority', models.IntegerField(blank=True, null=True, verbose_name='priority')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
            ],
            options={
                'verbose_name': 'Procedure',
                'verbose_name_plural': 'Procedure',
                'ordering': ['-created'],
            },
        ),
    ]
