# Generated by Django 4.1.4 on 2023-06-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('sucursal', models.IntegerField(primary_key=True, serialize=False)),
                ('camara', models.IntegerField()),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('host', models.CharField(blank=True, max_length=15, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('sdk', models.CharField(blank=True, max_length=120, null=True)),
                ('user', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
                ('fps', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('enable', models.CharField(blank=True, max_length=45, null=True)),
                ('recycle_mode', models.CharField(blank=True, max_length=45, null=True)),
                ('recycle_status', models.CharField(blank=True, max_length=45, null=True)),
                ('first_video', models.DateTimeField(blank=True, null=True)),
                ('last_video', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'camara',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CamarasPrv',
            fields=[
                ('sucursal', models.IntegerField(primary_key=True, serialize=False)),
                ('c1', models.CharField(blank=True, max_length=16, null=True)),
                ('c2', models.CharField(blank=True, max_length=16, null=True)),
                ('c3', models.CharField(blank=True, max_length=16, null=True)),
                ('c4', models.CharField(blank=True, max_length=16, null=True)),
                ('c5', models.CharField(blank=True, max_length=16, null=True)),
                ('c6', models.CharField(blank=True, max_length=16, null=True)),
                ('c7', models.CharField(blank=True, max_length=16, null=True)),
                ('c8', models.CharField(blank=True, max_length=16, null=True)),
                ('c9', models.CharField(blank=True, max_length=16, null=True)),
                ('c10', models.CharField(blank=True, max_length=16, null=True)),
                ('c11', models.CharField(blank=True, max_length=16, null=True)),
                ('c12', models.CharField(blank=True, max_length=16, null=True)),
                ('c13', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'camaras_prv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CamaraVideoLost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.IntegerField()),
                ('camara', models.IntegerField()),
                ('segmento_inicio', models.DateTimeField(blank=True, null=True)),
                ('segmento_fin', models.DateTimeField(blank=True, null=True)),
                ('tiempo_total', models.FloatField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'camara_video_lost',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccionamiento',
            fields=[
                ('sucursal', models.IntegerField(primary_key=True, serialize=False)),
                ('gateway', models.CharField(blank=True, max_length=16, null=True)),
                ('xvr', models.CharField(blank=True, max_length=120, null=True)),
                ('xvr_port', models.IntegerField(blank=True, null=True)),
                ('xvr_user', models.CharField(blank=True, max_length=45, null=True)),
                ('xvr_password', models.CharField(blank=True, max_length=45, null=True)),
                ('alarma', models.CharField(blank=True, max_length=16, null=True)),
                ('control_acceso', models.CharField(blank=True, max_length=16, null=True)),
                ('syncroback', models.CharField(blank=True, max_length=16, null=True)),
                ('switch', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'direccionamiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionamientoPrv',
            fields=[
                ('id_sedena', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('centro_costos', models.IntegerField(blank=True, null=True)),
                ('sucursal', models.CharField(blank=True, max_length=120, null=True)),
                ('gw', models.CharField(blank=True, max_length=15, null=True)),
                ('xvr', models.CharField(blank=True, max_length=15, null=True)),
                ('cam1', models.CharField(blank=True, max_length=15, null=True)),
                ('cam2', models.CharField(blank=True, max_length=15, null=True)),
                ('cam3', models.CharField(blank=True, max_length=15, null=True)),
                ('cam4', models.CharField(blank=True, max_length=15, null=True)),
                ('cam5', models.CharField(blank=True, max_length=15, null=True)),
                ('cam6', models.CharField(blank=True, max_length=15, null=True)),
                ('alarma', models.CharField(blank=True, max_length=15, null=True)),
                ('control_acceso', models.CharField(blank=True, max_length=15, null=True)),
                ('syncroback', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'direccionamiento_prv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('centro_costos', models.IntegerField(primary_key=True, serialize=False)),
                ('id_sedena', models.CharField(blank=True, max_length=10, null=True)),
                ('sucursal', models.CharField(blank=True, max_length=120, null=True)),
                ('semana', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('dummy', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha1', models.DateField(blank=True, null=True)),
                ('fecha2', models.DateField(blank=True, null=True)),
                ('dummy2', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre1', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre2', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre3', models.CharField(blank=True, max_length=45, null=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'entregas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('sucursal', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=45)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'process_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SbLogistica',
            fields=[
                ('centro_costos', models.IntegerField(primary_key=True, serialize=False)),
                ('id_sedena', models.CharField(blank=True, max_length=12, null=True)),
                ('sucursal', models.CharField(blank=True, max_length=120, null=True)),
                ('calle', models.CharField(blank=True, max_length=120, null=True)),
                ('numero', models.CharField(blank=True, max_length=45, null=True)),
                ('colonia', models.CharField(blank=True, max_length=120, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('entre_calle', models.CharField(blank=True, max_length=120, null=True)),
                ('y_calle', models.CharField(blank=True, max_length=120, null=True)),
                ('municipio', models.CharField(blank=True, max_length=120, null=True)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
                ('latitud', models.CharField(blank=True, max_length=45, null=True)),
                ('longitud', models.CharField(blank=True, max_length=45, null=True)),
                ('sb', models.CharField(blank=True, max_length=45, null=True)),
                ('bloque', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'sb_logistica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('sucursal', models.IntegerField(primary_key=True, serialize=False)),
                ('sedena', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('fase', models.IntegerField(blank=True, null=True)),
                ('implementacion', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('lastupdate', models.DateTimeField(blank=True, db_column='lastUpdate', null=True)),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Syncroback',
            fields=[
                ('centro_costos', models.IntegerField(primary_key=True, serialize=False)),
                ('id_sedena', models.CharField(blank=True, max_length=10, null=True)),
                ('sucursal', models.CharField(blank=True, max_length=120, null=True)),
                ('enviado', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('no_serie', models.CharField(blank=True, max_length=45, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'syncroback',
                'managed': False,
            },
        ),
    ]
