# Generated by Django 4.1.4 on 2023-07-04 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('servicio', models.IntegerField(primary_key=True, serialize=False, verbose_name='Servicio')),
                ('descripcion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Descripcion')),
                ('tiempo_de_toleracia', models.IntegerField(blank=True, null=True, verbose_name='Tiempo de tolerancia')),
                ('servidor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Servidor')),
                ('puerto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Puerto')),
                ('bd', models.CharField(blank=True, max_length=50, null=True, verbose_name='BD')),
                ('tabla', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tabla')),
                ('columna', models.CharField(blank=True, max_length=50, null=True, verbose_name='Columna')),
                ('usuario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuario')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Password')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('ultima_vez_activo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ultima vez activo')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creacion')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-created'],
            },
        ),
    ]
