# Generated by Django 4.1.4 on 2023-07-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='password',
            field=models.CharField(blank=True, default='Null', max_length=50, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='servicio',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='status',
            field=models.CharField(blank=True, default='Null', max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='ultima_vez_activo',
            field=models.CharField(blank=True, default='Null', max_length=50, null=True, verbose_name='Ultima vez activo'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='usuario',
            field=models.CharField(blank=True, default='Null', max_length=50, null=True, verbose_name='Usuario'),
        ),
    ]
