# Generated by Django 4.1.4 on 2023-07-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_alter_servicio_password_alter_servicio_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre'),
        ),
    ]
