# Generated by Django 4.1.4 on 2023-07-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0004_alter_servicio_descripcion_alter_servicio_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion'),
        ),
    ]
