# Generated by Django 4.1.4 on 2023-01-26 16:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
       
    ]

    operations = [
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('sitio', models.IntegerField(primary_key=True, serialize=False, verbose_name='Sitio')),
                ('proyecto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Proyecto')),
                ('ip', models.CharField(blank=True, max_length=80, null=True, verbose_name='Ip')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('is_alive', models.CharField(blank=True, max_length=50, null=True, verbose_name='Is alive')),
                ('last_update', models.DateTimeField(verbose_name='Last update')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creacion')),
                ('videoencode_config_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_sitio', to='monitor.videoencode', verbose_name='Configuracion de video')),
            ],
            options={
                'verbose_name': 'Sitio',
                'verbose_name_plural': 'Sitios',
                'ordering': ['-created'],
            },
        ),
    ]
