# Generated by Django 4.1.4 on 2023-02-02 19:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('Compression', models.CharField(blank=True, default='H.264', max_length=100, null=True, verbose_name='Compression')),
                ('resolution', models.CharField(blank=True, default='720p', max_length=100, null=True, verbose_name='Resolution')),
                ('SmartCodec', models.CharField(blank=True, default='Off', max_length=100, null=True, verbose_name='SmartCodec')),
                ('FPS', models.IntegerField(blank=True, default=4, null=True, verbose_name='FPS')),
                ('BitRateControl', models.CharField(blank=True, default='VBR', max_length=100, null=True, verbose_name='BitRateControl')),
                ('Quality', models.IntegerField(blank=True, default=4, null=True, verbose_name='Quality')),
                ('BitRate', models.IntegerField(blank=True, default=512, null=True, verbose_name='BitRate')),
                ('VideoEnable', models.CharField(blank=True, default='true', max_length=20, null=True, verbose_name='Video Enable')),
                ('Language', models.CharField(blank=True, default='English', max_length=100, null=True, verbose_name='Language')),
                ('CurrentTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CurrentTime')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
            ],
            options={
                'verbose_name': 'Config',
                'verbose_name_plural': 'Config',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('sitio', models.IntegerField(primary_key=True, serialize=False, verbose_name='Sitio')),
                ('proyecto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Proyecto')),
                ('ip', models.CharField(blank=True, max_length=80, null=True, verbose_name='Ip')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('is_alive', models.CharField(blank=True, max_length=50, null=True, verbose_name='Is alive')),
                ('last_update', models.DateTimeField(verbose_name='Last update')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creacion')),
            ],
            options={
                'verbose_name': 'Sitio',
                'verbose_name_plural': 'Sitios',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
                ('id_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_stream', to='sitios.config', verbose_name='Config')),
            ],
            options={
                'verbose_name': 'Stream',
                'verbose_name_plural': 'Streams',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_channel', to='sitios.sitio', verbose_name='Sitio')),
                ('streams', models.ManyToManyField(to='sitios.stream', verbose_name='Streams')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channel',
                'ordering': ['-created'],
            },
        ),
    ]
