# Generated by Django 4.1.4 on 2023-01-27 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitio',
            name='videoencode_config_id',
        ),
    ]
