# Generated by Django 4.1.4 on 2023-01-27 17:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0002_remove_sitio_videoencode_config_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('Compression', models.CharField(default='H.264', max_length=100, verbose_name='Compression')),
                ('CustomResolutionName', models.CharField(blank=True, default='720p', max_length=100, null=True, verbose_name='Numero de serie')),
                ('SmartCodec', models.CharField(default='Off', max_length=100, verbose_name='SmartCodec')),
                ('FPS', models.IntegerField(default=4, verbose_name='FPS')),
                ('BitRateControl', models.CharField(default='VBR', max_length=100, verbose_name='BitRateControl')),
                ('Quality', models.IntegerField(default=4, verbose_name='Quality')),
                ('BitRate', models.IntegerField(default=512, verbose_name='BitRate')),
                ('VideoEnable', models.CharField(blank=True, default='true', max_length=20, null=True, verbose_name='Video Enable')),
                ('Language', models.CharField(default='English', max_length=100, verbose_name='Language')),
                ('CurrentTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CurrentTime')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
                ('sitio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_config', to='sitios.sitio', verbose_name='Sitio')),
            ],
            options={
                'verbose_name': 'Config',
                'verbose_name_plural': 'Config',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
                ('id_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_stream', to='sitios.config', verbose_name='Config')),
            ],
            options={
                'verbose_name': 'Stream',
                'verbose_name_plural': 'Streams',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
                ('id_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_channel', to='sitios.config', verbose_name='Config')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channel',
                'ordering': ['-created'],
            },
        ),
    ]
