# Generated by Django 4.1.4 on 2023-01-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0003_config_stream_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='id_config',
        ),
        migrations.RemoveField(
            model_name='config',
            name='sitio_id',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='description',
        ),
        migrations.AddField(
            model_name='channel',
            name='sitios',
            field=models.ManyToManyField(to='sitios.sitio', verbose_name='Sitios'),
        ),
        migrations.AddField(
            model_name='channel',
            name='streams',
            field=models.ManyToManyField(to='sitios.stream', verbose_name='Streams'),
        ),
        migrations.AddField(
            model_name='config',
            name='TypeStream',
            field=models.CharField(default='MainFormat', max_length=100, verbose_name='TypeStream'),
        ),
    ]
