# Generated by Django 4.1.4 on 2023-01-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0004_remove_channel_id_config_remove_config_sitio_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='TypeStream',
        ),
    ]
