# Generated by Django 4.1.4 on 2023-01-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0006_alter_config_bitrate_alter_config_bitratecontrol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='CustomResolutionName',
        ),
        migrations.AddField(
            model_name='config',
            name='resolution',
            field=models.CharField(blank=True, default='720p', max_length=100, null=True, verbose_name='Resolution'),
        ),
    ]
