# Generated by Django 4.1.4 on 2023-01-27 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0007_remove_config_customresolutionname_config_resolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='sitios',
        ),
        migrations.AddField(
            model_name='channel',
            name='sitio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='get_channel', to='sitios.sitio', verbose_name='Sitio'),
            preserve_default=False,
        ),
    ]
