# Generated by Django 4.1.4 on 2023-06-21 00:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('hostname', models.CharField(max_length=50, verbose_name='Hostname')),
                ('ip', models.CharField(max_length=50, verbose_name='Direccion ip')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
            ],
            options={
                'verbose_name': 'DNS',
                'verbose_name_plural': 'DNSs',
                'ordering': ['-created'],
            },
        ),
    ]
