# Generated by Django 4.1.4 on 2023-01-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channel',
            new_name='ChannelB',
        ),
        migrations.AlterModelOptions(
            name='channelb',
            options={'ordering': ['-created'], 'verbose_name': 'ChannelB', 'verbose_name_plural': 'ChannelB'},
        ),
    ]
