# Generated by Django 4.1.4 on 2023-01-31 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('Compression', models.CharField(blank=True, default='H.264', max_length=100, null=True, verbose_name='Compression')),
                ('resolution', models.CharField(blank=True, default='720p', max_length=100, null=True, verbose_name='Resolution')),
                ('SmartCodec', models.CharField(blank=True, default='Off', max_length=100, null=True, verbose_name='SmartCodec')),
                ('FPS', models.IntegerField(blank=True, default=4, null=True, verbose_name='FPS')),
                ('BitRateControl', models.CharField(blank=True, default='VBR', max_length=100, null=True, verbose_name='BitRateControl')),
                ('Quality', models.IntegerField(blank=True, default=4, null=True, verbose_name='Quality')),
                ('BitRate', models.IntegerField(blank=True, default=512, null=True, verbose_name='BitRate')),
                ('VideoEnable', models.CharField(blank=True, default='true', max_length=20, null=True, verbose_name='Video Enable')),
                ('Language', models.CharField(blank=True, default='English', max_length=100, null=True, verbose_name='Language')),
                ('CurrentTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CurrentTime')),
                ('priority', models.IntegerField(blank=True, default=1, null=True, verbose_name='Priority')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
            ],
            options={
                'verbose_name': 'DefaultConfig',
                'verbose_name_plural': 'DefaultConfigs',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('usuario', models.CharField(max_length=200, verbose_name='Usuario')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
                ('ip', models.CharField(max_length=50, verbose_name='Servidor')),
                ('puerto', models.IntegerField(default=0, verbose_name='Puerto')),
                ('serial_no', models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='Numero de serie')),
                ('deviceType', models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='DeviceType')),
                ('status', models.CharField(blank=True, default='0', max_length=50, null=True, verbose_name='Status')),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='Last update')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-created'],
            },
        ),
    ]
