# Generated by Django 4.1.4 on 2023-02-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='puerto',
            field=models.IntegerField(verbose_name='Puerto'),
        ),
    ]
