# Generated by Django 4.1.4 on 2023-02-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_alter_device_puerto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultconfig',
            name='created',
            field=models.DateTimeField(verbose_name='Fecha creacion'),
        ),
    ]
