# Generated by Django 4.1.4 on 2023-06-21 00:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('sucursal', models.IntegerField(primary_key=True, serialize=False, verbose_name='Sucursal')),
                ('nombre', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre')),
                ('fase', models.IntegerField(blank=True, null=True, verbose_name='fase')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Model')),
                ('last_update', models.DateTimeField(verbose_name='Last update')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creacion')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Model')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_camera', to='sucursales.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Camera',
                'ordering': ['-created'],
            },
        ),
    ]
